language: android

dist: trusty

# By default, we get an older version of libstdc++6 so we need to update it for CMake.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools > /dev/null
  # Install the emulator system image, NDK, and CMake
  - sdkmanager "system-images;android-18;default;armeabi-v7a" ndk-bundle "cmake;3.10.2.4988404" > /dev/null
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - $(cd "$ANDROID_HOME/tools" && emulator -avd test -no-audio -no-window) &

install:
  - ./gradlew build assembleAndroidTest

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  # We have to explicitly specify connectedCheck on the 'tests' module as it will fail if it is run
  # on the 'duktape' module, despite not actually having any androidTest sources.
  - ./gradlew :duktape:connectedCheck

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "BP4x4YVhnMfezSiOoxjYZFm5WpjF5Qa2RvJ841q6vj0yTCmfkyw9F8JNloQpVHgy9pIXABXaxykEV4ddPNuQ/uru/1NalPLPMOjY+S+8kNSRtwH14aLEQVPSxZp2zEuAQIzKY0tW6drh9z2pfZoCqko6cH8h+hWwLs3SGsFrAJ8hJTl3ROe/vTkOKw/Ec1FNgT667nxlK/Q2uQWA5CNvjjDIMtOOEnXKO90jdq4PIIPrbLfeusTDShjMK8ltUtFRs7P84gCKZ3HWbIVdHHzLtP700E+jllB3AID6s/wMV8ExoNXKOjwDuOpkkK48K6F23uRQ1VdCpAL+DiBALiOwqevn2Ifo6qoEBD+ZoKeb5YrK2YRkn13QbWc+1rO//NFGIZzsRI0WsnhQLDOC8PWz4uesyI5wRV7jYtG4o6rDLiwAgutJZZCSPX4YRnfgkP1Usa5F8JM9P0zg61ZbsTQC+AXkgQUNq7WrvJE9UmAJsf1M4dzYZDlpTlCqUkyDa57LYhbg4Lqk6hCCV3vRcMCtPFIZvwDPSo309zQjkhK8TZbUKx3ZoWgXphJcm9Mdmqan2wMgOzMweIJ46f5sQX5r1jPvPTDukxilnpv8ijHTxshRlHUpQp4biaFw4cAJmJtkCiL4OrKLu1gp/v/+axFiwZiTJVSFYEaAvioTVU44ic4="
    - secure: "VSUjkbwVilSXzhe9oV/2WaRZ/a3cnAMT/MrKtTaxnRPhTOg7IcLnl986Y9Spg2grP3bgzFbJbcxcDte+kuOM7xas5BLoYdbeQW7FSuaP5ATNIRknDXp6TVe2T3zIZ2iwWJRFkKy3eyYbPNbwDEwI77WbuWRUlCFkjWuMg/mMy3BtBH2bCW4riPe5h8WeW0NzJv/1XpcZyUqJRLcDM6a9V9UNnHZigQmFb87id6Jp3OKjb39M4MSEzSVuUDP4JnV7/OJetbVD1bd0PVpDb38zfbczS2lcz0EsddL76zagYxxvST0Mfi2QkKhFgDABc0QaXckR3TGGljlBScZj34shqFQ5xQnSCCFQ75HCClgCylEYPngSjPQnfRUafI+6pP6VK1dwG6kwhO5cd2UYq9lDVYcGQ6cszKDF46gjTq2/uHw5gked0ZDS3n8MTp043OsETtFzA1aqk7jhNpa4ADb89STbjRVT66SiLlfwBU4HyufexNg5RKBIeORksJB8TDN/F8aij6bPtRHeEaV99cEgQFu4H5qXchQD37DwnGiJ8nFW2/XMom2cqKcp57z5UacLezLkEV1uhdaudCCsfj0da5W3Df9n8adEOeZvJPoZN4CZaGJ50yoD9MO7XG0Lc7qBqW28DIf9ArabLL6cJrwU9EybJZqzZftslgp7yKb/vsw="

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
